baseurl = "https://gdi.nbis.se"
title = "GDI datasets"
languageCode = "en-us"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination


[params]
  header_image = "img/gdi-logo.png"
  SEOTitle = "GDI Sweden datasets"
    slogan = "Demo site for GDI landing pages using HUGO"

  image_404 = "img/404-bg.jpg"

  # Sidebar settings
  sidebar_about_description = "GDI Sweden dataset description pages"
  sidebar_avatar = "img/gdi-logo.png"      # use absolute URL, seeing it's used in both `/` and `/about/`


[[params.addtional_menus]]